import FloatingDots from "./_components/FloatingDots";
import "./globals.css";

export const metadata = {
  title: "Oluwafisayo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className="fixed inset-0 z-0">
        <FloatingDots />
      </div>
      <body className="relative z-10">{children}</body>
    </html>
  );
}
